FROM ubuntu:jammy

# Ubuntu required arguments & variables
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US
ENV LC_ALL=en_US.UTF-8

# Update OS packages & clean cache
RUN apt-get update -y && \
	apt-get upgrade -y && \
	apt-get install -y --no-install-recommends locales python3 python3-distutils python3-pip python3-apt python-is-python3 && \
	# Configure locales
	locale-gen en_US.UTF-8 && \
	# Remove the cached files.
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /var/cache/apt/archives

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt .
COPY securityhub-cli.py .

# Install Python dependencies for scripts, etc.
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt --upgrade && rm requirements.txt

# CMD ["python", "securityhub-cli.py", "--help"]
